### PR TITLE
Remove different timeframe for Masternode Polls

### PR DESCRIPTION
**Pull request by ghost**
For simplicity, all proposal types should stay on the same 30 day timeframe. Generally the advantage of quicker decisions is outweighed by the disadvantage of a more complex governance system overall, with multiple timeframes, both in code and socially.

For example, many MNO only pay attention once a month, if governance polls were on a separate timeframe they would be settled before many MNO even saw them.

Also the advantage of quicker decisions applies equally to funding proposals as it does to decision polls, but 30 days is what we have and are used to. Unless it’s a problem, it should not be changed. 

There is nothing special about decision polls that justify the increased complexity of implementing a separate governance timeframe for them.

### CODE REVIEW

**Comment by jhodges10** [comment]
@bitedgecom this is something I want to discuss some more with others as I can see arguments on both sides here.

I don't think the technical implementation would add too much complexity to be honest. 

If you take into account all the upcoming changes to governance between Dash Nexus, delegated voting, and this - it's my expectation that the active voting body will be more involved going forwards than they have been in the past.

Just yesterday I ran into a scenario where this would be useful. Having to wait 30 days every time you need to make a decision in the world of crypto where things move as fast as they do is a problem. Even a 14 day voting period is still pretty slow for some things.

**Comment by ghost** [comment]
We want the result of these polls to be as authoritative as possible. That will be determined by how many masternodes participate. Having a poll with an end date other than the standard governance cycle will get less participants and therefore be less authoritative.

The result of any poll with a voting deadline other than the standard governance cycle will be undermined as being "snuck through undercover with only x% of masternodes knowing about it".

Also one of the points critics will make against this proposal is that governance polls may as well be off the blockchain. Platforms like the dash forum, dash central and dash nexuses could easily run polls that can only be voted on by cryptographically verified masternode owners (or their delegates).

That argument against these proposed on chain polls is made stronger by having them on a different time frame because it would make the polls more different and separate then the existing governance system anyway.

> between Dash Nexus, delegated voting, and this - it's my expectation that the active voting body will be more involved going forwards 

That's conjecture, all of those things don't exist and we don't know if they ever do exist how much use, if any, they will get. 

> I ran into a scenario where this would be useful...

Everyone who ever made a tresury proposal would have found it useful to get a faster decision. That applies to everything, polls are not different and separate, we want them to be as less different and separate as possible because different and separate increases code and social complexity. 

> Just yesterday I ran into a scenario where this would be useful. Having to wait 30 days every time you need to make a decision in the world of crypto where things move as fast as they do is a problem. Even a 14 day voting period is still pretty slow for some things.

By putting these polls on the same timeframe as the rest of the governance system one would not have to wait 30 days, one would have to wait for a voting deadline that occurs once every 30 days. If one creates a poll in the 21st day of a voting cycle one would have to wait 9 days. Just like current governance (tresury) proposals. 

So is your proposal to have a poll voting deadline cycles every 14 days so multiple polls created in that period have the same voting deadline? Or is your proposal for polls have a voting deadline 14 days after they are created so there is no regular poll deadline cycle?

**Comment by jhodges10** [comment]
@bitedgecom I've thought about what you said a lot over the past 10 days and I'm still not sure if I agree with you.

Another proposed change to governance that I've seen floated by two devs at this point is a rolling treasury that continually gets filled up and can be spent whenever a proposal receives enough votes to pass.

With that as context, what I'm proposing seems much less crazy.

That being said, I don't think it's asking too much of MNO to check in twice a month. To clarify, my two week long voting period for this polls is just about having a cycle that's 16616 / 2 blocks long.

**Comment by jhodges10** [comment]
If we had off-chain polling, it would also never get the level of credibility that an "on-chain poll" would.

**Comment by ghost** [comment]
> With that as context, what I'm proposing seems much less crazy.

That context is 100% conjecture. 

> I don't think it's asking too much of MNO to check in twice a month

You are asking them to check 3 times a month, 

* Day 14 (poll day)
* Day 28 (poll day)
* Day (30 tresury vote day)

If there is to be a shorter cycle it should be 15 days so every 2nd one syncs with the tresury vote cycle.  

How much it asked compared to what you think is too much is not relevant, how much it asks compared to how much the rest of the governance system asks is relevant. The rest of the governance systems asks MNO to do something once every 30 days. 

Someone who thinks it should be the same 30 day cycle as the rest of the governance system (in this case me) does not have to show why. 

Some who thinks it should be anything other that he same 30 day cycle as the rest of the governance system (in this case @jhodges10 ) does have to show why.

I am advocating for not departing from the norm, which does not need a reason.

You are advocating for a departing from the norm. That needs a reason. 

And I don't see one, you have the circular truism that it gives faster decisions. That is true, so would

29 days
28 days
27 days
...
13 days
12 days
11 days
...

**Comment by jhodges10** [comment]
Let me just clarify, I'm talking about 16616 blocks / 2 = 8,308 blocks or 15 days - not 14. I misspoke there.

The reason for that is that it would allow for code re-use (which is a big part of what I've proposed in fact). 

As for that context being conjecture, I've seen the code - it would work if deployed. I don't think it's really fair to call it conjecture just because you disagree with it.

**Pull request merged**
